### ISSUE TITLE
[feature] can use double quoted string as key of object (like JSON)

### ISSUE THREAD

**Issue by xieyuheng** [cicada-lang/cicada-plct#39]

**Comment by xieyuheng** [comment]
Since any double quoted string can be used as key.

We also need to support new syntax for `Dot`.

```
f["hello, world!"]
```

**Comment by LittleJianCH** [comment]
Is this syntax designed to support JSON?

**Comment by xieyuheng** [comment]
Yes, one aim of our design is to write JSON directly in our language.

**Comment by LittleJianCH** [comment]
We're unable to create an object with a field called `"hello, world!"` as in this case because of the space.

Should we add a feature that we can write object like the code below?
```
let obj = {
  "hello, world": String
}
```
