### ISSUE TITLE
[feature] equivalence

### ISSUE THREAD

**Issue by xieyuheng** [cicada-lang/cicada-plct#43]
**Problem:**

We need a built-in type for equivalence.

**Solution 1:**

Implement "the little typer"-like `Equal`:

- `Equal`
- `Replace`
- `Refl`
- `Same`

**Comment by ice1000** [comment]
I highly recommend a modern identity type (beyond jmeq or mltt id). Quotients and funExt are essential.

**Comment by xieyuheng** [comment]
**Solution 2:**

Implement a modern identity type.

(Maybe @ice1000 can suggest something (papers, books, talks, lectures) where we can learn from.)

**Comment by ice1000** [comment]
I suggest observational equality by McBride or cubical extension type (either cartesian or de morgan)

**Comment by xieyuheng** [comment]
Solution 1 implemented: https://github.com/cicada-lang/cicada/commit/86e60a30f2e1eafe8876e0cabbd0d71279fc9515

We will explore modern identity type in another issue.

**Comment by xieyuheng** [comment]
- https://github.com/cicada-lang/cicada/discussions/110
