### ISSUE TITLE
[feature] unification between two `Sigma`s

### ISSUE THREAD

**Issue by xieyuheng** [cicada-lang/cicada-plct#53]
**Problem:**

Suppose we have the following definition of `my_car` and `my_cdr`:

```ts
function my_car(
  implicit A: Type,
  implicit B: (x: A) -> Type,
  pair: exists (x: A) B(x)
): A {
  return car(pair)
}

function my_cdr(
  implicit A: Type,
  implicit B: (x: A) -> Type,
  pair: exists (x: A) B(x),
): B(car(pair)) {
  return cdr(pair)
}
```

Given `my_car(cons("a", "b"))`,
we can `infer` `cons("a", "b")` to be `exists (_: String) String`.

Then we must be able to solve the following equation:

```ts
solve (A: Type, B: (x: A) -> Type) {
  unify exists (x: A) B(x) = exists (_: String) String
}
```

The same problem occurs for unification between two `Pi`s.

**Comment by xieyuheng** [comment]
**Solution 1:**

Handle unification between `Sigma` specially,
to generate a const function `(x: String) => String` for `B`:

```ts
{
  A: String,
  B: (x: String) => String,
}
```

**Comment by xieyuheng** [comment]
**Solution 2:**

We might implement constraints-based unification.

To handle the following in general:

```js
solve (B: (x: String) -> Type) {
  unify B(x) = String
}
```

This time, we can not generate a const function,
instead we need to view `B(x) = String` as a constraint.

**Comment by ice1000** [comment]
> **Solution 2:**
> 
> We might implement constraints-based unification.

I have a feeling that this is just pattern unification. Can you tell me what makes it different?

**Comment by xieyuheng** [comment]
Given `my_car(cons("a", "b"))`,
instead of `infer` `cons("a", "b")` to be `exists (_: String) String`,
and solve the above equation.

We might get the following equation:

```ts
solve (A: Type, B: (x: A) -> Type) {
  unify B("a") = String
}
```

For which, the const function `(x: String) => String` is just one special solution.

**Comment by ice1000** [comment]
But it looks like the most general solution isn't it?

**Comment by xieyuheng** [comment]
@ice1000 Yes, it is.

**Comment by ice1000** [comment]
@xieyuheng So, in case of multiple solutions, it is sound to always pick the most general one (if exists), no?

**Comment by xieyuheng** [comment]
@ice1000 Oh, I was wrong.

It is not the most general solution, it is just the most simple function (the const function).

Since const function is not more general nor less general than other functions,
the solution with const functions is not the most general solution.

**Comment by xieyuheng** [comment]
https://github.com/cicada-lang/cicada/commit/ad9d69a41c7cb40f94d1db2d2748bc6716b0abe2

**Comment by ice1000** [comment]
Cool!!
