### ISSUE TITLE
[maybe] do not need `freshen` in `readback` and `deepWalk`

### ISSUE THREAD

**Issue by xieyuheng** [cicada-lang/cicada-plct#97]
We need to prove it is safe to not use `freshen`,
maybe in a simplified project
with only untyped lambda calculus and NbE.

**Comment by jwyjohn** [comment]
I wrote a python script to generate ramdom untyped lambda expression:
```
def genlmd(var, exp):
    return ["λ", [var], exp]

def genap(f, v):
    return [f, v]

def genexp(vars, pl, pe):
    r = random()
    ret = None
    if r < pl:
        ret = genlmd(choice(vars), genexp(vars, pl, pe))
    elif r < pl + pe:
        ret = genap(genexp(vars, pl, pe), genexp(vars, pl, pe))
    else:
        ret = choice(vars)
    return ret
```
The generated expressions are then normalized using untyped lambda calculus NbE interpreters with/without `freshen` in their readback.

After `~1000000` expressions are normalized, we did not find any difference between NbE interpreters with `freshen` and NbE interpreters without `freshen`.

**Comment by xieyuheng** [comment]
@jwyjohn thanks for this report，i will try to reproduce your result

**Comment by xieyuheng** [comment]
```
(lambda (x) ((lambda (f x) (f x)) x))

with freshen:
  (lambda (x1) (lambda (x) (x1 x)))

without freshen:
  (lambda (x) (lambda (x) (x x)))
```

test: https://github.com/cicada-lang/cicada/commit/4e5b69d97c22eca00080094b24957af79f57c45e

playground: https://cicada-lang.org/playground/ZnVuY3Rpb24gZih4OiAoVHlwZSkgLT4gVHlwZSk6IChUeXBlKSAtPiBUeXBlIHsKICBsZXQgZiA9IHgKICByZXR1cm4gdGhlKChUeXBlKSAtPiBUeXBlLCAoeCkgPT4gZih4KSkKfQoKY29tcHV0ZSBm
